### ISSUE TITLE
Node.js Foundation Website Redesign Strategic Initiative Meeting 2018-06-21

### ISSUE THREAD

**Issue by mhdawson** [nodejs/website-redesign#57] opened 2018-06-18 12:05 UTC
## Time

**UTC Thu 21-Jun-2018 14:00 (02:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Thu 21-Jun-2018 07:00 (07:00 AM) |
| US / Mountain | Thu 21-Jun-2018 08:00 (08:00 AM) |
| US / Central  | Thu 21-Jun-2018 09:00 (09:00 AM) |
| US / Eastern  | Thu 21-Jun-2018 10:00 (10:00 AM) |
| London        | Thu 21-Jun-2018 15:00 (03:00 PM) |
| Amsterdam     | Thu 21-Jun-2018 16:00 (04:00 PM) |
| Moscow        | Thu 21-Jun-2018 17:00 (05:00 PM) |
| Chennai       | Thu 21-Jun-2018 19:30 (07:30 PM) |
| Hangzhou      | Thu 21-Jun-2018 22:00 (10:00 PM) |
| Tokyo         | Thu 21-Jun-2018 23:00 (11:00 PM) |
| Sydney        | Fri 22-Jun-2018 00:00 (12:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Website%20Redesign%20Strategic%20Initiative+Meeting+2018-06-21&iso=20180621T14
* or http://www.wolframalpha.com/input/?i=02PM+UTC%2C+Jun+21%2C+2018+in+local+time

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/1mHAVh2TUxX-hxCXqQwCUODAaEmmnpkmEsYWQRA2ceC4/edit>

## Agenda

Extracted from **wr-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/website-redesign

* Node.js Extended Color Palette  [#42](https://github.com/nodejs/website-redesign/issues/42)
* Appreciation / Thank You [#59](https://github.com/nodejs/website-redesign/issues/59)
* Getting Started Titles [#60](https://github.com/nodejs/website-redesign/issues/60)

## Invited

* Website Redesign Strategic Initiative Team: @nodejs/website-redesign

## Notes

The agenda comes from issues labelled with `wr-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: Will be added a few minutes before meeting starts
* For those who just want to watch:
* youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

**Comment by keywordnew** [comment] 2018-06-20 16:12
I won't be able to make this meeting. There's a scheduling conflict that I couldn't get around.

Right now, I'm working on getting turning the data we gathered from the Collab Summit into individual issues that can be grabbed and worked on. I'm sorry it's taking longer than I estimated!!! I'm hoping it's not as much of a bottleneck as I feel it is 🙏🏽

**Comment by codeekage** [comment] 2018-06-21 13:49
I will dropping-in for today's meeting :tada:

**Comment by amiller-gh** [comment] 2018-06-21 14:02
@bnb will you be joining and streaming the Zoom meeting for us today?

**Comment by maddhruv** [comment] 2018-06-21 14:02
Are we doing this today? @amiller-gh @chowdhurian

**Comment by amiller-gh** [comment] 2018-06-21 14:03
We are, waiting on the Zoom link from Tierney 🙂 Just confirmed that he's on his way!

**Comment by bnb** [comment] 2018-06-21 14:04
Join link: https://zoom.us/j/108249750

**Comment by Belar** [comment] 2018-06-23 12:20
YouTube recording: https://youtu.be/zhkuG8c-VmA

**Comment by sagirk** [comment] 2018-06-24 05:08
Thanks for sharing @Belar!

**Comment by bnb** [comment] 2018-08-16 15:15
Going to close this for now since this meeting is past – feel free to re-open or create new issues if anything is still unresolved 😄

**Closed as completed by bnb** 2018-08-16 15:15 UTC
